/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Food;

/**
 *
 * @author Dell
 */
public class ViewFood extends javax.swing.JFrame {

    /**
     * Creates new form ViewFood
     */
    public ViewFood() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtVID = new javax.swing.JTextField();
        btnVSearch = new javax.swing.JButton();
        btnVFetch = new javax.swing.JButton();
        btnVDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnVBurgers = new javax.swing.JButton();
        btnVRolls = new javax.swing.JButton();
        btnVBuns = new javax.swing.JButton();
        btnVRice = new javax.swing.JButton();
        btnVSandwich = new javax.swing.JButton();
        btnVKottu = new javax.swing.JButton();
        btnVNoodles = new javax.swing.JButton();
        btnVPizza = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnVCutlet = new javax.swing.JButton();
        btnVPastry = new javax.swing.JButton();
        btnVMilk = new javax.swing.JButton();
        btnVDrinks = new javax.swing.JButton();
        btnVSweets = new javax.swing.JButton();
        btnVSoft = new javax.swing.JButton();
        btnVBday = new javax.swing.JButton();
        btnVCake = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableview = new javax.swing.JTable();
        btnVHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(101, 34, 72));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("View Food Details");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Product ID");

        txtVID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        btnVSearch.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnVSearch.setText("Search");

        btnVFetch.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnVFetch.setText("Fetch ALL");

        btnVDelete.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnVDelete.setText("Delete Item");

        jPanel2.setBackground(new java.awt.Color(130, 43, 112));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnVBurgers.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        btnVBurgers.setText("Burgers");

        btnVRolls.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        btnVRolls.setText("Rolls");

        btnVBuns.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        btnVBuns.setText("Buns");

        btnVRice.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        btnVRice.setText("Fried rice");

        btnVSandwich.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        btnVSandwich.setText("Sandwitches");

        btnVKottu.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        btnVKottu.setText("Kottu");

        btnVNoodles.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        btnVNoodles.setText("Noodles");

        btnVPizza.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        btnVPizza.setText("Mini Pizza");

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("Search By Category");

        btnVCutlet.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        btnVCutlet.setText("Cutlets");

        btnVPastry.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        btnVPastry.setText("Pastries");

        btnVMilk.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        btnVMilk.setText("Milk packets");

        btnVDrinks.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        btnVDrinks.setText("Other drinks");
        btnVDrinks.setToolTipText("");

        btnVSweets.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        btnVSweets.setText("Sweets");

        btnVSoft.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        btnVSoft.setText("Soft Drinks");

        btnVBday.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        btnVBday.setText("Bday cakes");

        btnVCake.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        btnVCake.setText("Cake pieces");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(102, 102, 102))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVPastry)
                    .addComponent(btnVNoodles)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnVCutlet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addComponent(btnVRolls, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnVBurgers)
                    .addComponent(btnVKottu, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVSweets)
                    .addComponent(btnVBuns, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVMilk)
                    .addComponent(btnVBday, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVRice, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVSandwich)
                    .addComponent(btnVCake, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVDrinks)
                    .addComponent(btnVSoft, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVBurgers)
                    .addComponent(btnVSandwich))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVPastry)
                    .addComponent(btnVRice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVKottu)
                    .addComponent(btnVPizza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVNoodles)
                    .addComponent(btnVBday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVRolls)
                    .addComponent(btnVCake))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVCutlet)
                    .addComponent(btnVMilk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVBuns)
                    .addComponent(btnVDrinks))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVSweets)
                    .addComponent(btnVSoft))
                .addGap(42, 42, 42))
        );

        tableview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Name", "Price", "Supplier", "Food Category", "Available for"
            }
        ));
        jScrollPane1.setViewportView(tableview);

        btnVHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\icons8-home-48 (1).png")); // NOI18N
        btnVHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2)
                            .addGap(24, 24, 24)
                            .addComponent(txtVID, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(btnVSearch)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVFetch))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btnVDelete)))
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVHome)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVHome))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtVID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVSearch)
                            .addComponent(btnVFetch))
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVDelete)
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVHomeActionPerformed
        HomeFood gh = new HomeFood();
        gh.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnVHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewFood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVBday;
    private javax.swing.JButton btnVBuns;
    private javax.swing.JButton btnVBurgers;
    private javax.swing.JButton btnVCake;
    private javax.swing.JButton btnVCutlet;
    private javax.swing.JButton btnVDelete;
    private javax.swing.JButton btnVDrinks;
    private javax.swing.JButton btnVFetch;
    private javax.swing.JButton btnVHome;
    private javax.swing.JButton btnVKottu;
    private javax.swing.JButton btnVMilk;
    private javax.swing.JButton btnVNoodles;
    private javax.swing.JButton btnVPastry;
    private javax.swing.JButton btnVPizza;
    private javax.swing.JButton btnVRice;
    private javax.swing.JButton btnVRolls;
    private javax.swing.JButton btnVSandwich;
    private javax.swing.JButton btnVSearch;
    private javax.swing.JButton btnVSoft;
    private javax.swing.JButton btnVSweets;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableview;
    private javax.swing.JTextField txtVID;
    // End of variables declaration//GEN-END:variables
}
