/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Food;

import DatabaseConnection.DBconnect;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class ViewFoodManager extends javax.swing.JFrame {

    /**
     * Creates new form ViewFood
     */
    public ViewFoodManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtVID = new javax.swing.JTextField();
        btnVSearch = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        comboVCategory = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btnVFetch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableview = new javax.swing.JTable();
        btnVDelete = new javax.swing.JButton();
        btnVClear = new javax.swing.JButton();
        btnHomePage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setText("View Food Details");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Product ID");

        txtVID.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtVID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVIDKeyTyped(evt);
            }
        });

        btnVSearch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnVSearch.setText("Search");
        btnVSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVSearchActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Category");

        comboVCategory.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        comboVCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Burgers", "Pastries", "Kottu", "Sandwiches", "Fried rice", "Mini Pizza", "Birthday cakes", "Cake Pieces", "Noodles", "Rolls", "Ctlets", "Buns", "Sweets", "Milk Packets", "Other drinks", "Soft Drinks" }));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnVFetch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnVFetch.setText("Fetch ALL");
        btnVFetch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVFetchActionPerformed(evt);
            }
        });

        tableview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Name", "Price", "Supplier", "Food Category", "Available for"
            }
        ));
        jScrollPane1.setViewportView(tableview);

        btnVDelete.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnVDelete.setText("Delete Item");
        btnVDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVDeleteActionPerformed(evt);
            }
        });

        btnVClear.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnVClear.setText("Clear Items");
        btnVClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVClearActionPerformed(evt);
            }
        });

        btnHomePage.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnHomePage.setText("Back");
        btnHomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomePageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnVDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnVFetch, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnVClear, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnHomePage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtVID, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnVSearch)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(comboVCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtVID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnVSearch))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(comboVCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(51, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVFetch, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnVDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnVClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomePageActionPerformed
        HomeFood hf = new HomeFood();
        hf.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnHomePageActionPerformed

    private void btnVDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVDeleteActionPerformed

        try {

            DefaultTableModel dtm = (DefaultTableModel) tableview.getModel();

            int selectedRow = tableview.getSelectedRow();
            String id = (String) dtm.getValueAt(selectedRow, 0);

            String query = "DELETE FROM fooditems WHERE fid='" + id + "'";
            DBconnect.sendQuery(query);

            dtm.removeRow(selectedRow);

            JOptionPane.showMessageDialog(null, "Item Deleted", "Information", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Failed To Deleted", "Error", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_btnVDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {

            String category1 = (String) comboVCategory.getSelectedItem();

            String query = "SELECT * FROM fooditems WHERE category='" + category1 + "'";
            ResultSet rs = DBconnect.search(query);

            while (rs.next()) {

                String fid = rs.getString("fid");
                String name = rs.getString("name");
                String price = rs.getString("price");
                String supplier = rs.getString("supplier");
                String category = rs.getString("category");
                String time = rs.getString("available");

                Object[] row = {fid, name, price, supplier, category, time};

                DefaultTableModel dtm = (DefaultTableModel) tableview.getModel();

                dtm.addRow(row);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error "+e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnVClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVClearActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) tableview.getModel();
        dtm.setRowCount(0);
    }//GEN-LAST:event_btnVClearActionPerformed

    private void btnVFetchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVFetchActionPerformed

        try {

            String query = "SELECT * FROM fooditems";
            ResultSet rs = DBconnect.search(query);

            while (rs.next()) {

                String fid = rs.getString("fid");
                String name = rs.getString("name");
                String price = rs.getString("price");
                String supplier = rs.getString("supplier");
                String category = rs.getString("category");
                String time = rs.getString("available");

                Object[] row = {fid, name, price, supplier, category, time};

                DefaultTableModel dtm = (DefaultTableModel) tableview.getModel();

                dtm.addRow(row);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error "+e);
        }

    }//GEN-LAST:event_btnVFetchActionPerformed

    private void btnVSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVSearchActionPerformed

        try {

            String id = txtVID.getText();

            String query = "SELECT * FROM fooditems WHERE fid='" + id + "'";
            ResultSet rs = DBconnect.search(query);

            while (rs.next()) {

                String fid = rs.getString("fid");
                String name = rs.getString("name");
                String price = rs.getString("price");
                String supplier = rs.getString("supplier");
                String category = rs.getString("category");
                String time = rs.getString("available");

                Object[] row = {fid, name, price, supplier, category, time};

                DefaultTableModel dtm = (DefaultTableModel) tableview.getModel();

                dtm.addRow(row);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnVSearchActionPerformed

    private void txtVIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVIDKeyTyped
        if (evt.getID() == KeyEvent.KEY_TYPED) {
            char inputChar = evt.getKeyChar();
            if (inputChar >= '0' && inputChar <= '9') {
                String text = txtVID.getText() + inputChar;
                System.out.println("Number :- " + Integer.parseInt(text));
            } else {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtVIDKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFoodManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFoodManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFoodManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFoodManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ViewFoodManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHomePage;
    private javax.swing.JButton btnVClear;
    private javax.swing.JButton btnVDelete;
    private javax.swing.JButton btnVFetch;
    private javax.swing.JButton btnVSearch;
    private javax.swing.JComboBox<String> comboVCategory;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableview;
    private javax.swing.JTextField txtVID;
    // End of variables declaration//GEN-END:variables
}
